server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8080 #Adjust this port to point to target service port
          predicates:
            - Path=/orders/**
          filters:
          - AddResponseHeader=author,balkrishan