server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: http://localhost:8080
          Predicates:
            - Path: /orders/**
          filters:
            -AddResponseHeader=author,balkrishan
