server:
  port: 8081

spring:
  cloud:
    gateway:
      default-filters:
        - name: OAuthFilter
      routes:
        - id: orders_route
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - AddResponseHeader=author,balkrishan
            - TokenRelay
        - id: auth_route
          uri: http://localhost:8080
          predicates:
            - Path=/oauth2/**

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080
